[workspace]
default-members = [
	"lexer",
	"parser",
	"context",
	"context/macros",
	"cli",
	"analyzer",
	"compiler",
	"vm",
]
members = [
	"lexer",
	"parser",
	"context",
	"context/macros",
	"cli",
	"analyzer",
	"compiler",
	"vm",
]
resolver = "2"
