[package]
name = "cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
context = { path = "../context" }
parser = { path = "../parser" }
analyzer = { path = "../analyzer" }
ast = { path = "../ast" }

rustyline = { version = "11.0.0", features = ["custom-bindings"] }
miette = { version = "5.9.0", features = ["fancy"] }
thiserror = "1.0.38"
dbg-pls = { version = "0.3.5", features = ["pretty", "colors"] }
clap = { version = "4.2.2", features = ["derive"] }
