[package]
edition = "2021"
name = "fuzz"
version = "0.1.0"

[package.metadata]
cargo-fuzz = true

[[bin]]
name = "parse"
path = "fuzz_targets/parse.rs"

[dependencies]
libfuzzer-sys = "0.4"
parser = { path = "../parser" }

[workspace]
