name: C++ CI

on:
  push:
    paths:
      - 'vm/**'
    branches:
      - master
  pull_request:
    paths:
      - 'vm/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compiler:
          - { c: gcc-10, cpp: g++-10 }
          - { c: gcc-12, cpp: g++-12 }
          - { c: clang-14, cpp: clang++-14 }
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}
    steps:
      - uses: actions/checkout@v4

      # Work around https://github.com/actions/runner-images/issues/8659
      - name: Remove GCC 13 from runner image
        if: matrix.compiler.c == 'clang-14'
        run: |
          sudo rm -f /etc/apt/sources.list.d/ubuntu-toolchain-r-ubuntu-test-jammy.list
          sudo apt-get update
          sudo apt-get install -y --allow-downgrades libc6=2.35-0ubuntu3.4 libc6-dev=2.35-0ubuntu3.4 libstdc++6=12.3.0-1ubuntu1~22.04 libgcc-s1=12.3.0-1ubuntu1~22.04

      - name: Build Debug
        run: |
          cd vm
          cmake -B build -S .
          cmake --build build

      - name: Build Release
        run: |
          cd vm
          cmake -DCMAKE_BUILD_TYPE=Release -B build -S .
          cmake --build build
