name: PR check format

on:
  pull_request_target:
    types: [review_requested]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always


jobs:
  check-format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Clone base
      run: | 
       mkdir /tmp/repo
       find -type f \( -name "*.rs" -o -name "*.[hc]pp" -o -name "*.[hc]" \) | {
          while read F; do
              mkdir -p $(dirname /tmp/repo/$F) && cp $F /tmp/repo/$F
          done 
       }

    - name: Format
      run: cargo fmt; cd vm && make format

    - name: Compare
      run: |
        - find -type f \( -name "*.rs" -o -name "*.[hc]pp" -o -name "*.[hc]" \) | {
          while read F; do
            if ! diff $F /tmp/repo/$F; then exit 1; fi
          done
        }
        
