name: Rust CI

on:
  push:
    paths: 
      - '**.rs'
      - '**.cpp'
      - '**.h'
      - '**/Cargo.toml'
  pull_request:
    paths:
      - '**.rs'
      - '**.cpp'
      - '**.h'
      - '**/Cargo.toml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Cargo Cache
      uses: actions/cache@v3
      with:
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.toml') }}
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
          
    - name: Build
      run: cargo build 
      
    - name: Run tests
      run: cargo test --verbose
