name: Rust CI

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Rust toolchain and cache
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt

    - name: Build
      run: |
        cargo build
        cargo bench --no-run --profile test

    - name: Run tests
      run: cargo test --verbose

    - name: Rustfmt Check
      uses: actions-rust-lang/rustfmt@v1
      continue-on-error: true

    - name: Clippy Check
      run: cargo clippy --tests
      continue-on-error: true

  build-macos:
    if: github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup toolchain and cache
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Build
      run: cargo build
