name: Rust CI

on:
  push:
    paths: 
      - '**.rs'
      - '**/Cargo.toml'
  pull_request:
    paths:
      - '**.rs'
      - '**/Cargo.toml'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    if: github.event_name != 'pull_request' || github.repository != github.event.pull_request.head.repo.full_name
    runs-on: ubuntu-latest
    steps:
    - uses: fkirc/skip-duplicate-actions@v5
    - uses: actions/checkout@v3
    
    - name: Cargo Cache
      uses: actions/cache@v3
      with:
        key: ${{ hashFiles('**/Cargo.toml') }}
        path: |
          ./target
          ~/.cargo
          
    - name: Build
      run: cargo build 
      
    - name: Run tests
      run: cargo test --verbose
